#!/bin/bash

if [ $# -eq 0 ]; then
  echo "Usage: factors <file>"
  exit 1
fi

while read -r line; do
  n=$line
  for (( i=2; i<=n; i++ )); do
    if (( n%i == 0 )); then
      p=$i
      q=$((n/p))
      echo "$n=$p*$q"
      break
    fi
  done
done < "$1"

